analyzer:
  errors:
    depend_on_referenced_packages: ignore
    deprecated_member_use: ignore
    unused_element: ignore
    unused_import: ignore
    use_build_context_synchronously: ignore

include: package:flutter_lints/flutter.yaml

formatter:
  page_width: 120
  trailing_commas: preserve

linter:
  rules:
  # avoid_print: false  # Uncomment to disable the `avoid_print` rule